# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Programming\Radio.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

try:
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import *
except ImportError:
    from PyQt4 import Qt, QtGui, QtCore
    from PyQt4.QtCore import *
    from PyQt4.QtGui import *

class Radio_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.gridLayout = QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.spectrum_layout = QVBoxLayout()       
        self.spectrum_layout.setObjectName("spectrum_layout")
        self.gridLayout.addLayout(self.spectrum_layout, 0, 0, 2, 1)
        self.controlbox = QGroupBox(Form)
        self.controlbox.setMinimumSize(QtCore.QSize(0, 0))
        self.controlbox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.controlbox.setObjectName("controlbox")
        self.formLayout = QFormLayout(self.controlbox)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QLabel(self.controlbox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label)
        self.frequency_spinbox = QDoubleSpinBox(self.controlbox)
        self.frequency_spinbox.setDecimals(3)
        self.frequency_spinbox.setMaximum(1700.0)
        self.frequency_spinbox.setProperty("value", 88.6)
        self.frequency_spinbox.setObjectName("frequency_spinbox")
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.frequency_spinbox)
        self.label_2 = QLabel(self.controlbox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_2)
        self.label_3 = QLabel(self.controlbox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_3)
        self.gain_cmb = QComboBox(self.controlbox)
        self.gain_cmb.setObjectName("gain_cmb")
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.gain_cmb)
        self.label_4 = QLabel(self.controlbox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_4)
        self.mode_cmb = QComboBox(self.controlbox)
        self.mode_cmb.setObjectName("mode_cmb")
        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.mode_cmb)
        self.label_5 = QLabel(self.controlbox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.label_5)
        self.agc_cmb = QComboBox(self.controlbox)
        self.agc_cmb.setObjectName("agc_cmb")
        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.agc_cmb)
        self.label_6 = QLabel(self.controlbox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.label_6)
        self.squelch_control = QSlider(self.controlbox)
        self.squelch_control.setMinimum(-130)
        self.squelch_control.setMaximum(400)
        self.squelch_control.setSingleStep(50)
        self.squelch_control.setProperty("value", -110)
        self.squelch_control.setOrientation(QtCore.Qt.Horizontal)
        self.squelch_control.setObjectName("squelch_control")
        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.squelch_control)
        self.label_7 = QLabel(self.controlbox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.label_7)
        self.af_control = QSlider(self.controlbox)
        self.af_control.setMaximum(400)
        self.af_control.setOrientation(QtCore.Qt.Horizontal)
        self.af_control.setObjectName("af_control")
        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.af_control)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QPushButton(self.controlbox)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.stop_btn = QPushButton(self.controlbox)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.formLayout.setLayout(8, QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_if_bw_wide = QRadioButton(self.controlbox)
        self.rb_if_bw_wide.setObjectName("rb_if_bw_wide")
        self.buttonGroup = QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_if_bw_wide)
        self.horizontalLayout_2.addWidget(self.rb_if_bw_wide)
        self.rb_if_bw_medium = QRadioButton(self.controlbox)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_if_bw_medium.sizePolicy().hasHeightForWidth())
        self.rb_if_bw_medium.setSizePolicy(sizePolicy)
        self.rb_if_bw_medium.setChecked(True)
        self.rb_if_bw_medium.setObjectName("rb_if_bw_medium")
        self.buttonGroup.addButton(self.rb_if_bw_medium)
        self.horizontalLayout_2.addWidget(self.rb_if_bw_medium)
        self.rb_if_bw_narrow = QRadioButton(self.controlbox)
        self.rb_if_bw_narrow.setObjectName("rb_if_bw_narrow")
        self.buttonGroup.addButton(self.rb_if_bw_narrow)
        self.horizontalLayout_2.addWidget(self.rb_if_bw_narrow)
        self.formLayout.setLayout(1, QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayout.addWidget(self.controlbox, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.controlbox.setTitle(_translate("Form", " Frequency Control "))
        self.label.setText(_translate("Form", "Frequency (MHz)"))
        self.label_2.setText(_translate("Form", "IF Bandwidth"))
        self.label_3.setText(_translate("Form", "Gain (dB)"))
        self.label_4.setText(_translate("Form", "Mode"))
        self.label_5.setText(_translate("Form", "AGC"))
        self.label_6.setText(_translate("Form", "Squlech Level"))
        self.label_7.setText(_translate("Form", "AF Gain"))
        self.start_btn.setText(_translate("Form", "Start"))
        self.stop_btn.setText(_translate("Form", "Stop"))
        self.rb_if_bw_wide.setText(_translate("Form", "W"))
        self.rb_if_bw_medium.setText(_translate("Form", "M"))
        self.rb_if_bw_narrow.setText(_translate("Form", "N"))

